name = "pluginify"
description = "Package Spin plugins for faster iteration"
version = { from = "Cargo.toml" }
spin_compatibility = ">=0.7"
license = "Apache-2.0"
package = "./target/release/pluginify"
